# Generated by Django 2.1.15 on 2021-05-12 19:36
import json
import os
import uuid

from django.db import migrations, models

def load_madrid_data(apps, schema_editor):
    file_path = f'{os.path.abspath(os.path.dirname(__name__))}/data/madrid_dea.json'
    with open(file_path, 'r') as madrid_json:
        json_data = json.load(madrid_json)

    dea_device_model = apps.get_model('desfibrimaps', 'DjangoDea')
    for madrid_dea in json_data.get('data'):
        dea_direccion = f'{madrid_dea.get("direccion_via_codigo", "")} {madrid_dea.get("direccion_via_nombre", "no data")}'
        device = dea_device_model.objects.create(
            id=uuid.uuid4(),
            locality=madrid_dea.get('municipio_nombre', 'Madrid'),
            address=dea_direccion,
            device_location=madrid_dea.get('direccion_ubicacion'),
            postal_code=madrid_dea.get('direccion_codigo_postal', "28012"),
            lat=madrid_dea.get('direccion_coordenada_y'),
            long=madrid_dea.get('direccion_coordenada_x'),
            ownership=madrid_dea.get('tipo_titularidad', "Privada"),
        )

class Migration(migrations.Migration):

    dependencies = [
        ('desfibrimaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangodea',
            name='ownership',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(load_madrid_data),
    ]
